services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "bridge"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/media:/media
    ports:
      - "8096:8096"    # Change if needed
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: "bridge"
    volumes:
      - ./radarr/config:/config
      - ./radarr/downloads:/downloads
      - ./radarr/movies:/movies
    ports:
      - "7878:7878"    # Change if needed
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "bridge"
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/downloads:/downloads
      - ./sonarr/tv:/tv
    ports:
      - "8989:8989"    # Change if needed
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    network_mode: "bridge"
    volumes:
      - ./prowlarr/config:/config
    ports:
      - "9696:9696"    # Change if needed
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    network_mode: "bridge"
    volumes:
      - ./jellyseerr/config:/app/config
    ports:
      - "5055:5055"    # Change if needed
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "bridge"
    volumes:
      - ./qbittorrent/appdata:/config
      - ./qbittorrent/downloads:/downloads #optional
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  # homepage:
  #   image: gethomepage/homepage
  #   container_name: homepage
  #   network_mode: "bridge"
  #   volumes:
  #     - ./homepage/config:/app/config
  #   ports:
  #     - "5055:5055"    # Change if needed
  #   restart: unless-stopped 

  homepage:
    image: gethomepage/homepage:latest
    container_name: homepage
    network_mode: "bridge"
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts